Fix QA environment variable check
In Ruby 3.1, `QA::Runtime::Env.enabled?` never worked properly
when a boolean default value was used:

```ruby
irb(main):010> (false =~ /^(false|no|0)$/i) != 0
=> true
irb(main):011> (true =~ /^(false|no|0)$/i) != 0
=> true
```

In Ruby 3.2, this results in a hard failure:

```ruby
irb(main):003> (false =~ /^(false|no|0)$/i) != 0
(irb):3:in `<main>': undefined method `=~' for false:FalseClass
   (NoMethodError)
```

Fix this by converting the value to a string.