Indicate requirement for OpenSSH 8.2
The existing documentation suggests OpenSSH 8.0 or newer, but when I follow these instructions and try to commit I encounter the error
```bash
$ git commit -am"blah"
error: ssh-keygen -Y sign is needed for ssh signing (available in openssh version 8.2p1+)
```
with
```bash
[cmartin3@cmartin3-ws mk1-sil]$ ssh -V
OpenSSH_8.0p1, OpenSSL 1.1.1k  FIPS 25 Mar 2021
[cmartin3@cmartin3-ws mk1-sil]$ cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```
I haven't updated to OpenSSH 8.2 specifically, but it does work if I update to OpenSSH 8.4, committing successfully and then showing **Verified** when pushed to the GitLab remote.