Make bundler-checksum work with Bundler v2.5.0 (part 2)
Bundler v2.5.0 introduced a CHECKSUMS section in Gemfile.lock and
significantly refactored checksums into `Bundler::Checksum`.  The
refactoring dropped the `Bundler::RubyGemsGemInstaller#checksum_type`
method, causing pre-install checks to fail with `NoMethodError:
undefined method 'checksum_type'` as seen in
https://gitlab.com/gitlab-org/gitlab/-/jobs/5861840560.

This commit fixes the digest comparison to use the digest set
in `Bundler::Checksum`. This change needs to be backwards
compatible with Bundler v2.4.x until we require v2.5.x.

Changelog: fixed